# Generated by Django 2.0.6 on 2018-06-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180627_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='product', max_length=200),
            preserve_default=False,
        ),
    ]
